Repository commaai/connect, pull requests merged in 2023-05, with the labels that each got.

#354 DriveVideo: show error message when video fails to load
  package.json
  src/components/DriveVideo/index.js
  src/components/DriveView/Media.js
  yarn.lock
Labels: bugfix

#355 DriveVideo: reset error on playback resume
  src/components/DriveVideo/index.js
Labels: bugfix

#356 move version (commit hash) to account menu
  src/components/AppDrawer/index.js
  src/components/AppHeader/index.js
Labels: enhancement

#357 clips: higher z-index for clip bounds sliders and position rect in timeline view
  src/components/Timeline/index.js
Labels: bugfix, clips

#359 DriveVideo: clear errors on playback start and buffer end
  src/components/DriveVideo/index.js
Labels: bugfix

#363 analytics: add FCP and TTFB web vitals
  src/analytics-v2.js
Labels: enhancement

#361 fix mouse navigation keys on timeline bug
  src/components/Timeline/index.js
Labels: bugfix
