Repository commaai/connect, pull requests merged in 2023-07, with the labels that each got.

#377 docker: use PR head sha
  .github/workflows/build.yaml
Labels: bugfix, CI / testing

#384 log app version to console
  src/App.jsx
  src/components/ServiceWorkerWrapper/index.jsx
  src/index.jsx
Labels: enhancement

#385 update TimeDisplay skip/rewind icons
  src/components/TimeDisplay/index.jsx
  src/icons/index.jsx
Labels: enhancement

#386 add Vite PWA plugin
  .eslintignore
  index.html
  nginx.conf
  package.json
  pnpm-lock.yaml
  public/favicon.svg
  public/icon-maskable.png
  public/icon-maskable.svg
  public/icon-vector.svg
  public/manifest.json
  public/robots.txt
  src/components/ServiceWorkerWrapper/index.jsx
  src/index.jsx
  src/serviceWorkerRegistration.js
  vite.config.js
Labels: enhancement

#389 add build timestamp information
  .github/workflows/build.yaml
  Dockerfile
  src/index.jsx
Labels: enhancement

#391 add build timestamp to account menu
  .github/workflows/build.yaml
  src/components/AppHeader/index.jsx
Labels: enhancement

#392 add simple error boundary
  package.json
  pnpm-lock.yaml
  src/components/explorer.jsx
  src/index.jsx
  tailwind.config.js
Labels: enhancement

#393 improved error boundary
  src/components/explorer.jsx
  src/icons/index.jsx
Labels: enhancement

#395 reset timeline loop
  src/reducers/globalState.js
Labels: bugfix

#398 ErrorBoundary: include service worker state
  src/App.jsx
  src/components/ErrorFallback.jsx
  src/components/explorer.jsx
Labels: enhancement

#397 DeviceList: fix iOS scroll refresh bug
  src/components/Dashboard/DeviceList.jsx
Labels: bugfix

#399 fix native pull down to refresh
  src/components/AppDrawer/index.jsx
  src/components/Dashboard/DeviceList.jsx
  src/index.css
Labels: bugfix

#409 split out AccountMenu from AppHeader
  src/components/AppHeader/AccountMenu.jsx
  src/components/AppHeader/index.jsx
  src/components/explorer.jsx
  tailwind.config.js
Labels: cleanup

#417 timeline: fix thumbnail image indices
  src/components/Timeline/thumbnails.jsx
Labels: bugfix
