Repository commaai/connect, pull requests merged in 2023-08, with the labels that each got.

#420 demo: new route
  lighthouserc.js
  src/__puppeteer__/demo.test.js
  src/__puppeteer__/offline.test.js
  src/__puppeteer__/routing.test.js
  src/demo/devices.json
  src/demo/index.js
  src/initialState.js
Labels: enhancement

#421 CI: reduce puppeteer test time from 34s to 13s
  src/__puppeteer__/.eslintrc.js
  src/__puppeteer__/demo.test.js
  src/__puppeteer__/offline.test.js
  src/__puppeteer__/routing.test.js
  src/__puppeteer__/utils.js
Labels: CI / testing

#419 timeline zoom stack
  src/__puppeteer__/drive.test.js
  src/actions/history.js
  src/actions/history.test.js
  src/actions/index.js
  src/actions/index.test.js
  src/actions/types.js
  src/analytics.js
  src/components/ClipView/ClipDone.jsx
  src/components/Dashboard/DriveListItem.jsx
  src/components/DriveView/index.jsx
  src/components/Timeline/index.jsx
  src/reducers/globalState.js
Labels: enhancement, refactor

#423 linting fixes
  .eslintrc.js
  src/App.jsx
  src/actions/cached.js
  src/actions/clips.js
  src/actions/files.js
  src/actions/index.js
  src/actions/types.js
  src/components/ClipView/ClipCreate.jsx
  src/components/ClipView/ClipDone.jsx
  src/components/ClipView/ClipUpload.jsx
  src/components/Dashboard/DeviceSettingsModal.jsx
  src/components/DeviceInfo/index.jsx
  src/components/DriveView/Media.jsx
  src/components/Navigation/index.jsx
  src/components/Prime/PrimeCheckout.jsx
  src/components/Prime/PrimeManage.jsx
  src/components/Timeline/index.jsx
  src/components/Timeline/thumbnails.jsx
  src/components/Timeline/thumbnails.test.js
  src/components/anonymous.jsx
  src/components/explorer.jsx
  src/reducers/globalState.js
  src/utils/array.js
Labels: cleanup

#425 DriveVideo: improved buffering logic
  src/components/DriveVideo/index.jsx
Labels: refactor

#428 navigation: fix duplicate place name in address
  src/components/Navigation/index.jsx
  src/components/Navigation/utils.js
  src/components/Navigation/utils.test.js
Labels: bugfix, nav
