Repository commaai/connect, pull requests merged in 2024-07, with the labels that each got.

#522 Only query single route if segmentRange specified
  package.json
  pnpm-lock.yaml
  src/actions/index.js
Labels: bugfix

#545 remove duplicate FILE_NAMES
  src/actions/files.js
  src/components/DriveView/Media.jsx
  src/components/Files/UploadQueue.jsx
Labels: cleanup

#546 support multiple possible file names
  src/actions/files.js
  src/components/DriveView/Media.jsx
  src/components/Files/UploadQueue.jsx
Labels: enhancement
