Repository commaai/connect, pull requests merged in 2025-03, with the labels that each got.

#201 test(geocode): remove whitehouse case, keeps changing
  src/map/geocode.spec.ts
Labels: CI / testing

#212 RouteActivity: updated toggles design
  src/components/RouteActions.tsx
Labels: design

#218 feat: format distance in km, detect region from navigator.language
  src/utils/format.ts
Labels: enhancement

#219 CI: exclude blank lines from line count
  src/ci/check_lines.ts
Labels: CI / testing

#216 feat: upload user files
  src/api/athena.ts
  src/api/devices.ts
  src/api/file.ts
  src/api/index.ts
  src/api/route.ts
  src/api/upload.ts
  src/ci/check_bundle_size.ts
  src/components/RouteActions.tsx
  src/components/RouteUploadButtons.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/types.d.ts
Labels: enhancement

#223 CI: update some actions, pin version
  .github/workflows/build.yaml
  .github/workflows/preview.yaml
  Dockerfile
Labels: CI / testing

#225 feat: notify device of viewed routes
  src/api/athena.ts
  src/pages/dashboard/activities/RouteActivity.tsx
Labels: enhancement

#228 perf: reduce Material Symbols font payload
  index.html
  src/components/material/Icon.tsx
  src/pages/auth/login.tsx
  vite.config.ts
Labels: enhancement

#230 chore: setup biome format, fix on commit
  .editorconfig
  .github/workflows/build.yaml
  .vscode/extensions.json
  biome.jsonc
  lefthook.yml
  package.json
  src/api/athena.ts
  src/api/auth/client.ts
  src/api/auth/index.ts
  src/api/derived.ts
  src/api/devices.ts
  src/api/file.ts
  src/api/index.ts
  src/api/prime.ts
  src/api/route.ts
  src/api/upload.ts
  src/ci/check_bundle_size.ts
  src/ci/dependency_report.ts
  src/ci/screenshots.ts
  src/components/DeviceLocation.tsx
  src/components/RouteActions.tsx
  src/components/RouteStaticMap.tsx
  src/components/RouteUploadButtons.tsx
  src/components/RouteVideoPlayer.tsx
  src/components/Timeline.tsx
  src/components/material/AppBar.tsx
  src/components/material/Avatar.tsx
  src/components/material/Button.tsx
  src/components/material/ButtonBase.tsx
  src/components/material/Card.tsx
  src/components/material/CircularProgress.tsx
  src/components/material/Drawer.tsx
  src/components/material/FloatingActionButton.tsx
  src/components/material/Icon.tsx
  src/components/material/IconButton.tsx
  src/components/material/LinearProgress.tsx
  src/components/material/List.tsx
  src/components/material/NavigationBar.tsx
  src/components/material/TopAppBar.tsx
  src/index.css
  src/map/geocode.spec.ts
  src/map/geocode.ts
  src/map/index.ts
  src/pages/auth/login.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/pages/dashboard/activities/PairActivity.css
  src/pages/dashboard/activities/PairActivity.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/pages/dashboard/components/DeviceList.tsx
  src/pages/dashboard/components/RouteList.tsx
  src/types.d.ts
  src/utils/createQuery.ts
  src/utils/device.ts
  src/utils/format.spec.ts
  src/utils/format.ts
  tailwind.config.ts
  vite.config.ts
  vitest.workspace.ts
Labels: CI / testing, dx

#231 refactor: add type-checked name prop to Icon component
  src/components/DeviceLocation.tsx
  src/components/RouteActions.tsx
  src/components/RouteStaticMap.tsx
  src/components/RouteUploadButtons.tsx
  src/components/material/Drawer.tsx
  src/components/material/Icon.tsx
  src/components/material/IconButton.tsx
  src/components/material/NavigationBar.tsx
  src/pages/auth/login.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/pages/dashboard/activities/PairActivity.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  vite.config.ts
Labels: dx

#232 chore: delete unused components
  src/components/material/NavigationBar.tsx
  src/components/material/Search.tsx
Labels: cleanup

#233 CI: comment lines diff
  .github/workflows/diff.yaml
  src/ci/check_lines.ts
Labels: CI / testing, dx

#235 fix: dont send upload request if there are no files to upload
  src/api/upload.ts
Labels: bugfix

#240 CI(diff): markdown table for PR review
  src/ci/check_lines.ts
Labels: enhancement, CI / testing

#239 refactor: create StatisticsBar
  src/components/DeviceStatistics.tsx
  src/components/RouteStatistics.tsx
  src/components/StatisticBar.tsx
  src/utils/format.spec.ts
  src/utils/format.ts
Labels: refactor

#241 CI(diff): properly report no changes
  src/ci/check_lines.ts
Labels: CI / testing, bugfix

#243 cleanup(dashboard): fetch devices where they are used
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/components/DeviceList.tsx
Labels: cleanup

#246 feat: add device unpair button
  src/api/devices.ts
  src/api/index.ts
  src/components/material/Icon.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
Labels: enhancement

#249 Dashboard: add account details
  src/components/material/Icon.tsx
  src/pages/dashboard/Dashboard.tsx
Labels: enhancement

#98 RouteList: add bookmark icon to flagged routes
  src/components/material/Avatar.tsx
  src/components/material/Icon.tsx
  src/pages/dashboard/components/RouteList.tsx
Labels: enhancement, design

#251 feat: upload queue
  src/components/UploadQueue.tsx
  src/components/material/Icon.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
Labels: enhancement

#256 feat: nice auth screen
  src/pages/auth/auth.tsx
Labels: enhancement, design

#265 fix: reset typography letter spacing
  tailwind.config.ts
Labels: bugfix, design

#266 fix: use correct auth API endpoint
  src/api/auth/client.ts
Labels: bugfix

#252 feat: implement PWA
  bun.lock
  package.json
  public/manifest.json
  src/App.tsx
  src/ci/check_bundle_size.ts
  src/components/material/Icon.tsx
  src/index.tsx
  src/pages/offline.tsx
  src/pwa.ts
  vite.config.ts
Labels: enhancement

#269 cleanup: remove unused components
  src/components/material/AppBar.tsx
  src/components/material/FloatingActionButton.tsx
Labels: cleanup

#275 fix: RouteVideoPlayer startTime prop sometimes NaN
  src/components/RouteVideoPlayer.tsx
Labels: bugfix

#276 test: fix App smoketest
  package.json
  src/App.browser.test.tsx
  src/App.tsx
  src/api/auth/demo.ts
  src/pages/auth/login.tsx
  vitest.workspace.ts
Labels: CI / testing, bugfix

#279 cleanup: simplify app testing
  src/App.browser.test.tsx
Labels: cleanup

#272 feat: poll offline queue
  src/ci/check_bundle_size.ts
  src/components/UploadQueue.tsx
Labels: enhancement

#200 fix: view shared devices
  src/App.browser.test.tsx
  src/api/devices.ts
  src/api/profile.ts
  src/api/route.ts
  src/components/RouteStatistics.tsx
  src/components/material/Icon.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
Labels: CI / testing, bugfix

#286 perf: lazy import Hls.js in RouteVideoPlayer
  src/components/RouteVideoPlayer.tsx
  src/hls-light-types.d.ts
  src/utils/hls.ts
Labels: enhancement

#289 Remove duplicate events.json queries
  src/components/RouteStatistics.tsx
  src/pages/dashboard/components/RouteList.tsx
Labels: bugfix

#287 feat: cancel item, all, w/ stats bar
  src/components/UploadQueue.tsx
Labels: enhancement

#293 ci: always deploy preview for PRs
  .github/workflows/preview.yaml
Labels: CI / testing

#294 ci: use 'biome ci' command
  .github/workflows/build.yaml
  .github/workflows/preview.yaml
Labels: CI / testing

#295 fix: show device stats if has device access
  src/api/devices.ts
  src/pages/dashboard/activities/DeviceActivity.tsx
Labels: bugfix

#315 api: getDerived should filter missing data
  src/api/derived.ts
Labels: bugfix

#317 cleanup: use fixed page size in RouteList
  src/pages/dashboard/components/RouteList.tsx
Labels: cleanup

#318 cleanup: fix types
  src/components/RouteStaticMap.tsx
  src/components/RouteStatistics.tsx
Labels: cleanup

#321 cleanup: return undefined for failed requests
  src/api/derived.ts
  src/api/devices.ts
  src/api/profile.ts
  src/api/route.ts
  src/components/DeviceLocation.tsx
  src/components/RouteActions.tsx
  src/components/RouteUploadButtons.tsx
  src/components/Timeline.tsx
  src/pages/dashboard/Dashboard.tsx
Labels: cleanup

#320 ./test.sh
  .github/workflows/build.yaml
  src/ci/check_bundle_size.ts
  test.ps1
  test.sh
  vitest.workspace.ts
Labels: CI / testing, dx

#323 refactor: re-write Timeline event handling
  src/components/Timeline.tsx
Labels: refactor

#325 cleanup: don't lazy import RouteVideoPlayer
  src/pages/dashboard/activities/RouteActivity.tsx
Labels: cleanup

#327 cleanup: simplify Timeline props, data loading
  src/components/Timeline.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
Labels: cleanup

#330 perf: avoid re-creating HLS.js instance
  src/components/RouteVideoPlayer.tsx
Labels: enhancement

#332 fix: firehose parsing
  src/components/UploadQueue.tsx
Labels: bugfix

#334 ci: check TypeScript type errors
  src/components/UploadQueue.tsx
  test.sh
  tsconfig.json
Labels: CI / testing, bugfix

#339 cleanup: use clearer types in RouteUploadButtons
  src/api/upload.ts
  src/components/RouteUploadButtons.tsx
Labels: cleanup

#348 cleanup: simpify upload button icon type
  src/components/RouteUploadButtons.tsx
Labels: cleanup

#349 chore: update live script
  live.sh
Labels: dx

#351 cleanup: simplify RouteUploadButtons file type logic
  src/components/RouteUploadButtons.tsx
Labels: cleanup

#340 fix: reset upload btn state on new route selection
  src/components/RouteUploadButtons.tsx
Labels: bugfix

#352 fix: concat usage
  src/components/RouteUploadButtons.tsx
Labels: bugfix

#358 test: include AppLayout in browser tests
  src/App.browser.test.tsx
  src/App.tsx
Labels: CI / testing

#366 cleanup: remove unused suspense
  src/pages/dashboard/activities/DeviceActivity.tsx
Labels: cleanup

#369 fix: remove Timeline event listeners on touchend
  src/components/Timeline.tsx
Labels: bugfix

#283 feat: integrated route video player
  src/components/RouteVideoPlayer.tsx
  src/components/Timeline.tsx
  src/components/material/Icon.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/utils/format.ts
  src/utils/hls.ts
Labels: enhancement, design

#370 fix: timeline cursor alignment
  src/components/Timeline.tsx
Labels: bugfix, design

#375 fix: don't try to parse JSON for missing files
  src/api/derived.ts
Labels: bugfix

#379 fix: update theme color to match background
  index.html
  public/manifest.json
Labels: bugfix

#378 design: white timeline progress bar
  src/components/Timeline.tsx
Labels: design

#268 design: user flag icon
  src/components/Timeline.tsx
  src/pages/dashboard/components/RouteList.tsx
Labels: design

#326 feat: setup `@tanstack/solid-query` for data fetching, use in upload queue
  bun.lock
  package.json
  src/App.tsx
  src/api/devices.ts
  src/api/query-client.ts
  src/ci/check_bundle_size.ts
  src/components/UploadQueue.tsx
Labels: enhancement

#387 refactor: move API types
  src/api/athena.ts
  src/api/derived.ts
  src/api/devices.ts
  src/api/file.ts
  src/api/profile.ts
  src/api/route.ts
  src/api/types.d.ts
  src/api/upload.ts
  src/components/RouteActions.tsx
  src/components/RouteStaticMap.tsx
  src/components/RouteStatistics.tsx
  src/components/RouteUploadButtons.tsx
  src/components/Timeline.tsx
  src/components/UploadQueue.tsx
  src/pages/dashboard/components/DeviceList.tsx
  src/pages/dashboard/components/RouteList.tsx
  src/utils/device.ts
  src/utils/format.ts
Labels: refactor

#388 refactor: merge api/upload with api/file
  src/api/athena.ts
  src/api/file.ts
  src/api/upload.ts
  src/components/RouteUploadButtons.tsx
  src/components/UploadQueue.tsx
Labels: refactor
