Repository commaai/connect, pull requests merged in 2025-04, with the labels that each got.

#398 fix: cant play / pause by clicking entire surface
  src/components/RouteVideoPlayer.tsx
Labels: bugfix

#400 RouteCard suspense
  src/pages/dashboard/components/RouteList.tsx
Labels: refactor

#402 refactor: create Sentinel component
  src/pages/dashboard/components/RouteList.tsx
Labels: refactor

#405 fix: segments numbers is maxqlog + 1
  src/api/derived.ts
Labels: bugfix

#411 fix: sentry release in build
  Dockerfile
  vite.config.ts
Labels: CI / testing, bugfix

#418 fix: correct path to Apple splash PWA assets
  pwa-assets.config.ts
Labels: bugfix

#440 cleanup: combined url state
  src/pages/dashboard/Dashboard.tsx
Labels: cleanup

#467 fix: remove extraneous SuspenseList in Dashboard
  src/pages/dashboard/Dashboard.tsx
Labels: bugfix

#491 fix: show video unsupported error message
  src/components/RouteVideoPlayer.tsx
Labels: bugfix

#492 ci: bring back playwright cache
  .github/workflows/build.yaml
  test.sh
Labels: CI / testing

#532 fix(timeline): clip marker to 0-100% range
  src/components/Timeline.tsx
Labels: bugfix

#528 feat(statistics): get route duration from log events
  src/api/derived.ts
  src/components/Timeline.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
Labels: enhancement

#530 feat(statistics): use log duration in route stats
  src/components/RouteStatisticsBar.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/components/RouteList.tsx
  src/utils/format.ts
Labels: enhancement

#535 cleanup(snapshot): move method to athena, use store
  src/api/athena.ts
  src/pages/dashboard/activities/DeviceActivity.tsx
Labels: cleanup

#538 fix: login redirect
  src/pages/dashboard/Dashboard.tsx
Labels: bugfix

#542 fix: rm smallest font size, use consistent font sizes across app
  src/components/DeviceLocation.tsx
  src/components/RouteActions.tsx
  src/components/RouteStaticMap.tsx
  src/components/StatisticBar.tsx
  src/components/UploadQueue.tsx
  src/pages/auth/auth.tsx
  src/pages/auth/login.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/pages/dashboard/activities/PairActivity.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/pages/dashboard/components/DeviceList.tsx
  src/pages/dashboard/components/RouteList.tsx
  src/pages/offline.tsx
  tailwind.config.ts
Labels: bugfix, design

#541 refactor: add reactivity helper isResolved
  src/api/profile.ts
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/utils/reactivity.ts
Labels: refactor

#540 fix(route): date loading
  src/api/route.ts
  src/pages/dashboard/activities/RouteActivity.tsx
Labels: bugfix, design

#543 cleanup: LinearProgress
  src/components/material/LinearProgress.tsx
Labels: cleanup

#544 fix(RouteVideoPlayer): ceil duration
  src/components/RouteVideoPlayer.tsx
Labels: bugfix, design

#548 refactor(auth): accessToken is a signal
  src/App.browser.test.tsx
  src/api/auth/client.ts
  src/api/index.ts
Labels: refactor

#552 fix(RouteList): increase subheading font size
  src/pages/dashboard/components/RouteList.tsx
Labels: bugfix, design

#555 fix: set max-width on Icon
  src/index.css
Labels: bugfix

#557 fix(PairActivity): catch errors starting QR scanner
  src/pages/dashboard/activities/PairActivity.tsx
Labels: bugfix

#562 cleanup(RouteUploadButtons): simplify store and types
  src/components/RouteUploadButtons.tsx
Labels: cleanup

#567 feat(UploadQueue): improve 'Cancel all' button style
  src/components/UploadQueue.tsx
  src/components/material/Button.tsx
  src/components/material/Icon.tsx
Labels: enhancement, design

#568 fix: don't show "no devices" until API response loaded
  src/pages/dashboard/Dashboard.tsx
Labels: bugfix

#570 feat(DeviceList): show fallback when empty
  src/pages/dashboard/components/DeviceList.tsx
Labels: enhancement

#571 feat: add first-time pairing instructions
  src/pages/dashboard/Dashboard.tsx
Labels: enhancement

#572 cleanup: remove API fetched_at and add Device.is_online
  src/api/devices.ts
  src/api/index.ts
  src/api/types.d.ts
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/pages/dashboard/components/DeviceList.tsx
  src/utils/device.ts
Labels: cleanup

#573 CI: add tsc problem matcher/annotations
  .github/tsc.json
  .github/workflows/build.yaml
Labels: CI / testing, dx

#575 fix(ci): don't build the app twice
  .github/workflows/build.yaml
Labels: CI / testing, bugfix

#574 feat(BuildInfo): show build date and commit
  .github/workflows/build.yaml
  src/components/BuildInfo.tsx
  src/pages/dashboard/Dashboard.tsx
Labels: enhancement

#578 refactor(SettingsActivity): create DeviceSettingsForm component
  src/pages/dashboard/activities/SettingsActivity.tsx
Labels: refactor

#579 refactor(Dashboard): shared data
  src/App.browser.test.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/pages/dashboard/activities/PairActivity.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/pages/dashboard/components/DeviceList.tsx
  src/pages/dashboard/data.ts
Labels: refactor

#576 feat: update device name
  src/api/devices.ts
  src/ci/check_bundle_size.ts
  src/components/material/TextField.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/pages/dashboard/store.ts
Labels: enhancement

#581 fix(Button): improved text btn contrast
  src/components/material/Button.tsx
Labels: bugfix, design

#583 fix: tailwind color definitions
  src/index.css
  tailwind.config.ts
Labels: bugfix

#585 fix(prime): improve copy and design of cancel dialog
  src/pages/dashboard/activities/SettingsActivity.tsx
Labels: bugfix, design

#586 fix(settings): use text style button
  src/pages/dashboard/activities/SettingsActivity.tsx
Labels: bugfix, design

#587 refactor(Dialog): add component, update design
  src/components/material/Dialog.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
Labels: refactor

#589 fix(Dialog): remove flex class, hidden by default
  src/components/material/Dialog.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
Labels: bugfix

#590 feat(settings): unpair confirmation dialog
  src/pages/dashboard/activities/SettingsActivity.tsx
Labels: enhancement

#591 feat(Device): add battery voltage indicator
  src/components/material/Icon.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
Labels: enhancement
