Repository commaai/connect, pull requests merged in 2025-01, with the labels that each got.

#118 statistics: fix wrapping issues
  src/components/DeviceStatistics.tsx
  src/components/RouteStatistics.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
  tailwind.config.ts
Labels: bugfix

#119 manifest: update theme and background colours
  public/manifest.json
Labels: enhancement

#120 refactor: CI dependency report
  .github/workflows/build.yaml
  src/ci/dependency_report.cjs
  src/ci/dependency_report.ts
Labels: CI / testing, refactor

#121 CI: update preview comment action
  .github/workflows/preview.yaml
Labels: CI / testing

#123 CI: use `gh pr view` to get PR number and avoid rate limit
  .github/workflows/preview.yaml
Labels: CI / testing

#122 screenshots: enable linting
  .github/workflows/preview.yaml
  src/ci/screenshots.ts
Labels: CI / testing

#127 test: use @vitest/browser and setup test linting
  .github/workflows/build.yaml
  bun.lockb
  eslint.config.js
  package.json
  src/App.browser.test.tsx
  src/App.test.tsx
  vite.config.ts
  vitest.workspace.ts
Labels: CI / testing, cleanup

#115 feat: show user and device location on map
  bun.lockb
  package.json
  src/App.tsx
  src/api/devices.ts
  src/components/DeviceLocation.tsx
  src/map/index.ts
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/types.d.ts
Labels: enhancement

#143 fix(timeline): prevent page scroll while dragging
  src/components/Timeline.tsx
Labels: bugfix

#147 fix(bundle-size): measure file size not disk usage
  check-bundle-size.sh
Labels: CI / testing, bugfix

#148 cleanup: use hls.js esm build, save a few kb
  bun.lockb
  package.json
  src/components/RouteVideoPlayer.tsx
  src/hls-light-types.d.ts
Labels: cleanup

#145 add sentry error monitoring
  .github/workflows/build.yaml
  .gitignore
  bun.lockb
  check-bundle-size.sh
  package.json
  src/index.tsx
  vite.config.ts
Labels: enhancement

#141 fix(PairActivity): video container layout
  src/pages/dashboard/activities/PairActivity.tsx
Labels: bugfix

#135 fix: buttons squished
  src/components/material/Button.tsx
  src/components/material/List.tsx
  src/pages/dashboard/Dashboard.tsx
Labels: bugfix

#149 update dependencies
  bun.lockb
  package.json
  src/index.tsx
Labels: enhancement
