Repository commaai/connect, pull requests merged in 2025-02, with the labels that each got.

#117 feat(RouteList): implement infinite scrolling
  src/pages/dashboard/components/RouteList.tsx
Labels: enhancement, design

#154 fix(RouteList): duplicate entries
  src/pages/dashboard/components/RouteList.tsx
Labels: bugfix

#156 cleanup: create DrawerContext for interacting with drawer
  src/components/material/Drawer.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/utils/useDeviceList.tsx
Labels: cleanup

#158 cleanup: inline components used in one place
  src/components/RouteCard.tsx
  src/pages/dashboard/components/DeviceList.tsx
  src/pages/dashboard/components/RouteList.tsx
  src/utils/useDeviceList.tsx
Labels: cleanup

#159 fix: bring back max width on desktop
  src/pages/dashboard/Dashboard.tsx
Labels: bugfix

#157 feat: use modal drawer on smaller screens
  src/components/material/Drawer.tsx
  src/pages/dashboard/Dashboard.tsx
Labels: enhancement, design

#160 Dashboard: use two pane layout on larger screens
  src/components/material/Drawer.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/pages/dashboard/components/ActivityBar.tsx
Labels: design

#163 fix(RouteList): adjust page size for screen height
  src/pages/dashboard/components/RouteList.tsx
Labels: bugfix

#162 dashboard redesign
  src/components/DeviceLocation.tsx
  src/components/RouteStaticMap.tsx
  src/components/material/ButtonBase.tsx
  src/components/material/Card.tsx
  src/components/material/List.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/DeviceActivity.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/pages/dashboard/components/ActivityBar.tsx
  src/pages/dashboard/components/DeviceList.tsx
  src/pages/dashboard/components/RouteList.tsx
Labels: design

#170 refactor: use mapbox v6 geocoding api
  bun.lockb
  package.json
  src/components/DeviceLocation.tsx
  src/map/api-types.ts
  src/map/geocode.spec.ts
  src/map/geocode.ts
  src/map/index.ts
  src/test/setup.ts
  vitest.workspace.ts
Labels: refactor

#174 test(date): add unix timestamp cases
  src/utils/date.spec.ts
  src/utils/date.ts
Labels: CI / testing

#176 fix: various text wrapping and overflow issues
  src/components/DeviceLocation.tsx
  src/components/material/Card.tsx
  src/components/material/IconButton.tsx
  src/components/material/List.tsx
  src/components/material/TopAppBar.tsx
  src/pages/dashboard/components/DeviceList.tsx
Labels: cleanup, bugfix

#177 refactor: rename date utils to format
  src/api/derived.ts
  src/components/DeviceStatistics.tsx
  src/components/RouteStatistics.tsx
  src/components/Timeline.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/utils/format.spec.ts
  src/utils/format.ts
Labels: refactor

#178 test(format): add unit tests for formatDistance/Duration
  src/components/RouteStatistics.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/utils/format.spec.ts
  src/utils/format.ts
Labels: CI / testing

#179 chore: use Bun shell for bundle check script
  .github/workflows/build.yaml
  bun.lockb
  check-bundle-size.sh
  package.json
  src/ci/check_bundle_size.ts
  src/ci/dependency_report.ts
  tsconfig.json
Labels: dx

#180 chore: use Bun shell for line count script
  .github/workflows/build.yaml
  check-lines.sh
  package.json
  src/ci/check_lines.ts
Labels: dx

#182 style: custom scrollbar
  src/index.css
Labels: design

#184 chore: replace ESLint with Biome
  .github/workflows/build.yaml
  .vscode/extensions.json
  biome.jsonc
  bun.lockb
  eslint.config.js
  lefthook.yml
  package.json
  postcss.config.cjs
  src/pages/auth/login.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/activities/PairActivity.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/pages/dashboard/activities/SettingsActivity.tsx
  src/utils/format.ts
Labels: CI / testing, cleanup

#185 fix(RouteList): add state-layer back to card
  src/components/material/Card.tsx
Labels: bugfix

#186 cleanup: remove unused surface component
  src/components/material/Surface.tsx
Labels: cleanup

#189 CI: cancel earlier PR preview jobs
  .github/workflows/preview.yaml
Labels: CI / testing, bugfix

#164 RouteInfo: add route action buttons
  src/api/config.ts
  src/api/route.ts
  src/components/RouteActions.tsx
  src/components/RouteInfo.tsx
  src/pages/dashboard/activities/RouteActivity.tsx
  src/types.d.ts
Labels: enhancement

#195 fix(RouteActions): wrap route ID when no space
  src/components/RouteActions.tsx
Labels: bugfix
